name: RLearn Multiple Tests

on:
  pull_request:
    paths:
      - 'rlearn/*'
      - 'test/config/*'
      - 'test/data/dss/*'
      - 'test/data/stb_skc/*'
      - '.github/workflows/RLearn_pytest.yml'

# Add these permissions
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test-SAR_data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.8']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install torch
        git clone https://github.com/open-starlab/RLearn.git
        cd ./RLearn
        pip install .
        
    - name: Run RLearn tests
      run: |
        pytest rlearn/sports/pytest_main_class.py -v

    - name: Report test results
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const output = `
          ####  RLearn Test Results 📝
          - Status: ${process.env.TEST_OUTCOME}
          - OS: ${{ runner.os }}
          - Python: ${{ matrix.python-version }}
          `;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
      env:
        TEST_OUTCOME: ${{ job.status }}